=== Boyarsky1997/greenhouse/src/main/resources/greenhouse.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="plants">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flowers" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="soil" type="xs:string"/>
                            <xs:element name="origin" type="xs:string"/>
                            <xs:element name="visual">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="stem_color" type="xs:string"/>
                                        <xs:element name="leaf_color" type="xs:string"/>
                                        <xs:element name="average_plant_size" type="xs:double" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="growingTips">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="temperature" type="xs:double" maxOccurs="60"/>
                                        <xs:element name="lighting">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="yes"/>
                                                    <xs:enumeration value="no"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="watering" type="xs:double"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="multiplying">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="листями"/>
                                        <xs:enumeration value="зернами"/>
                                        <xs:enumeration value="пагінцями"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Boyarsky1997/greenhouse/src/main/resources/greenhouse.xml
<?xml version="1.0" encoding="utf-8" ?>
<plants xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="greenhouse.xsd">
    <flower>
        <name>Кактус</name>
        <soil>Коричневий</soil>
        <origin>Мексика</origin>
        <visual>
            <stem_color>Зелений</stem_color>
            <leaf_color>Зелений</leaf_color>
            <average_plant_size>20.0</average_plant_size>
        </visual>
        <growing_tips>
            <temperature>35</temperature>
            <lighting>yes</lighting>
            <watering>15</watering>
        </growing_tips>
        <multiplying>пагінцями</multiplying>
    </flower>
    <flower>
        <name>Фі́кус</name>
        <soil>Чорнозем</soil>
        <origin>Азія</origin>
        <visual>
            <stem_color>Коричневий</stem_color>
            <leaf_color>Зелений</leaf_color>
            <average_plant_size>2</average_plant_size>
        </visual>
        <growing_tips>
            <temperature>20</temperature>
            <lighting>no</lighting>
            <watering>30</watering>
        </growing_tips>
        <multiplying>зернами</multiplying>
    </flower>
</plants>
